// swift-tools-version: 5.9
//
// Generated by pulse-ios-sdk release workflow (Scripts/release/sync-release-distribution.rb).
// Binary targets match PulseKit.podspec peers + PulseKit; paths are repo-root xcframeworks.

import PackageDescription

let package = Package(
    name: "PulseKitDistribution",
    platforms: [
        .iOS(.v15),
    ],
    products: [
        .library(name: "PulseKit", targets: ["PulseKitWrapper"]),
    ],
    dependencies: [],
    targets: [
.binaryTarget(
    name: "PulseKitBinary",
    path: "PulseKit.xcframework"
),
.binaryTarget(
    name: "OpenTelemetryApiBinary",
    path: "OpenTelemetryApi.xcframework"
),
.binaryTarget(
    name: "OpenTelemetrySdkBinary",
    path: "OpenTelemetrySdk.xcframework"
),
.binaryTarget(
    name: "SwiftProtobufBinary",
    path: "SwiftProtobuf.xcframework"
),
.binaryTarget(
    name: "KSCrashBinary",
    path: "KSCrash.xcframework"
),
.binaryTarget(
    name: "libwebpBinary",
    path: "libwebp.xcframework"
),
        .target(
            name: "PulseKitWrapper",
            dependencies: [
                "PulseKitBinary",
                "OpenTelemetryApiBinary",
                "OpenTelemetrySdkBinary",
                "SwiftProtobufBinary",
                "KSCrashBinary",
                "libwebpBinary",
            ],
            path: "Sources/PulseKitWrapper"
        ),
    ]
)
